### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by glenndierckx** [StevenThuriot/dotnet-openapi-generator#1]
Hi, I've tried to follow the getting started guide but failed to get it working.

Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-openapi-generator does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

**Comment by LieselThuriot** [comment]
Welp; That's annoying at best that Mac only supports `dotnet-` commands rather than any naming convention
